script: 'ci/travis.rb'
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
env:
  - "GEM=railties"
  - "GEM=ap,am,amo,as"
  - "GEM=ar:mysql"
  - "GEM=ar:mysql2"
  - "GEM=ar:sqlite3"
  - "GEM=ar:postgresql"
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
bundler_args: --path vendor/bundle --without test
